### PR TITLE
Correction.

### PR DESCRIPTION
**Pull request by adnasa**
... typo on the commit :sob:

### CODE REVIEW

**Comment by ericelliott** [comment]
Tests? =)

**Comment by adnasa** [comment]
bed time first :sleepy: 
i can't take another typo in my commits. good talk!

**Comment by ericelliott** [comment]
:+1:

**Comment by adnasa** [comment]
@ericelliott Added that test. Distinguishing lat / long is always fun, I guess.

**Comment by ericelliott** [comment]
LGTM @JedWatson =)

**Comment by JedWatson** [comment]
:+1: thanks @adnasa!

**Pull request merged**
