### PR TITLE
update limax and slug without tone number in pinyin

### PR DESCRIPTION
**Pull request by arthurtalkgoal**
Fix the tone numbers problem in https://github.com/lovell/limax/issues/4#event-317042267

### CODE REVIEW

**Comment by JedWatson** [comment]
Thanks @arthurtalkgoal! Can you rebase + update the PR please though? I can't merge it because of conflicts.

**Comment by arthurtalkgoal** [comment]
Sure @JedWatson , 

I rebased the commits. Is it ok now?

**Comment by grabbou** [comment]
Still this pull request cannot be merged.

**Comment by dcousens** [comment]
@arthurtalkgoal, are you sure you rebased on master?

**Comment by JedWatson** [comment]
Not sure why we're having merge issues, so I've just manually merged it. Thanks @arthurtalkgoal :)

**Comment by arthurtalkgoal** [comment]
Cool! I am checking and was master branch.

**Pull request closed without merging**
