### PR TITLE
use limax for slugs

### PR DESCRIPTION
**Pull request by arthurtalkgoal**
The quality of limax depends on cld.

But cld is very bad on finding e.g. traditional Chinese. Now I allow locale options to improve the quality

### CODE REVIEW

**Comment by JedWatson** [comment]
Unfortunately this commit has removed all the trailing whitespace, which makes the diff less clear than it should be. Would you mind resubmitting with just the lines you've changed please?

**Comment by JedWatson** [comment]
Actually, never mind!

I've been meaning to start stripping trailing whitespace from my projects anyway.

**Comment by dcousens** [comment]
@JedWatson add `?w=0` on to the diff url.

See https://github.com/keystonejs/keystone-utils/pull/11/files?w=0

**Comment by jossmac** [comment]
@dcousens that's a neat trick

**Pull request merged**
